import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
from typing import Union

class SingleRunPlotter:
    """
    Reads exported CSV metrics from a specific run directory and generates 
    corresponding matplotlib figures, saving them to the figures directory.
    """
    def __init__(self, run_dir: Union[Path, str], figures_dir: Union[Path, str]):
        self.run_dir = Path(run_dir)
        self.figures_dir = Path(figures_dir)
        self.figures_dir.mkdir(parents=True, exist_ok=True)
        
        # Use the folder name (e.g., 'run_id1') to prefix the saved figures
        self.run_id = self.run_dir.name 

    def plot_all(self) -> None:
        """Finds all CSVs in the run directory and routes them to the correct plotting function."""
        csv_files = list(self.run_dir.glob('*.csv'))
        
        if not csv_files:
            print(f"No CSV files found in {self.run_dir}")
            return

        for csv_path in csv_files:
            filename = csv_path.stem
            try:
                df = pd.read_csv(csv_path)
                
                # Determine plot type based on the columns generated by StatsExporter
                columns = df.columns.tolist()
                
                if 'From_Thread' in columns and 'To_Thread' in columns:
                    self._plot_2d_matrix(df, metric_name=filename)
                elif 'Thread_ID' in columns:
                    self._plot_1d_array(df, metric_name=filename)
                elif 'Metric' in columns:
                    self._plot_scalars(df, metric_name=filename)
                else:
                    print(f"Skipping {filename}: Unknown CSV structure.")
                    
            except Exception as e:
                print(f"Failed to plot {filename}: {e}")

    def _plot_1d_array(self, df: pd.DataFrame, metric_name: str) -> None:
        """Plots thread-level data as a bar chart with standard deviation error bars."""
        plt.figure(figsize=(10, 6))
        
        threads = df['Thread_ID'].astype(str)
        means = df['Average']
        stds = df['Standard_Deviation']

        plt.bar(threads, means, yerr=stds, capsize=5, color='skyblue', edgecolor='black')
        
        plt.title(f"{metric_name.replace('_', ' ').title()} ({self.run_id})", fontsize=14)
        plt.xlabel("Thread ID", fontsize=12)
        plt.ylabel("Average", fontsize=12)
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout()

        out_path = self.figures_dir / f"{self.run_id}_{metric_name}.png"
        plt.savefig(out_path, dpi=300)
        plt.close()
        print(f"Saved 1D plot: {out_path}")

    def _plot_2d_matrix(self, df: pd.DataFrame, metric_name: str) -> None:
        """Plots 2D transfer matrices as a heatmap."""
        plt.figure(figsize=(8, 6))
        
        # Pivot the flat CSV back into a 2D grid for the heatmap
        pivot_df = df.pivot(index='From_Thread', columns='To_Thread', values='Average')
        
        # Create heatmap
        plt.imshow(pivot_df, cmap='viridis', aspect='auto')
        cbar = plt.colorbar()
        cbar.set_label('Average Value', rotation=270, labelpad=15)
        
        # Format axes
        plt.title(f"{metric_name.replace('_', ' ').title()} ({self.run_id})", fontsize=14)
        plt.xlabel("To Thread", fontsize=12)
        plt.ylabel("From Thread", fontsize=12)
        
        # Ensure tick marks match thread IDs
        plt.xticks(ticks=np.arange(len(pivot_df.columns)), labels=pivot_df.columns.to_list())
        plt.yticks(ticks=np.arange(len(pivot_df.index)), labels=pivot_df.index.to_list())

        plt.tight_layout()
        out_path = self.figures_dir / f"{self.run_id}_{metric_name}.png"
        plt.savefig(out_path, dpi=300)
        plt.close()
        print(f"Saved 2D heatmap: {out_path}")

    def _plot_scalars(self, df: pd.DataFrame, metric_name: str) -> None:
        """
        Plots single-value summary metrics. 
        Because metrics might have drastically different scales (e.g., 0.12 vs 1500),
        this creates a horizontal bar chart with independent subplots for each metric.
        """
        num_metrics = len(df)
        fig, axes = plt.subplots(nrows=num_metrics, ncols=1, figsize=(8, 1.5 * num_metrics))
        
        # Handle case where there is only one metric (axes is not an array)
        if num_metrics == 1:
            axes = [axes]

        for ax, (_, row) in zip(axes, df.iterrows()):
            ax.barh([row['Metric']], [row['Average']], xerr=[row['Standard_Deviation']], capsize=5, color='coral', edgecolor='black')
            ax.set_title(row['Metric'].replace('_', ' ').title(), fontsize=10)
            ax.set_yticks([]) # Hide the y-axis label since the title explains it
            ax.grid(axis='x', linestyle='--', alpha=0.7)

        plt.suptitle(f"Summary Metrics ({self.run_id})", fontsize=14, y=1.02)
        plt.tight_layout()

        out_path = self.figures_dir / f"{self.run_id}_{metric_name}.png"
        plt.savefig(out_path, bbox_inches='tight', dpi=300)
        plt.close()
        print(f"Saved Scalar subplots: {out_path}")